#Note contains password
---
# - name: Wait for ssh connection
#  hosts: all
#  gather_facts: False
#  tasks:
#    - name: Ensure ssh port open
#      wait_for: 
#        port: 22
#        delay: 10    # seconds
#        timeout: 100 # seconds
#        search_regex: OpenSSH
#        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
#      vars:
#        ansible_connection: local
#        ansible_python_interpreter: /usr/bin/python


- name: Install python3, docker, Docker-compose, docker python module and start docker
  hosts: aws_ec2 # all
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3, docker, Docker-compose, docker python module and start docker
      vars:
        ansible_python_interpreter: /usr/bin/python 
      yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present      
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-{{lookup('pipe', 'uname -m')}} 
        dest: /usr/local/bin/docker-compose
        mode: +x    
    - name: Start docker daemon
      systemd: 
        name: docker
        state: started
    - name: Install docker python module
      pip: 
        name: 
          - docker
          - docker-compose
    

- name: Create new linux user
  hosts: aws_ec2 # all
  become: yes
  tasks:
    - name: Create new linux user
      user: 
        name: pedro
        groups: adm, docker




- name: Start docker containers
  hosts: aws_ec2 # all
  become: yes
  become_user: pedro  
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy: 
        src: /mnt/c/Users/MA/IdeaProjects/bootcamp-java-mysql/docker-compose.yaml
        dest: /home/pedro/docker-compose.yaml
    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/  # For Docker
        username: pmadev4
        password: "{{docker_password}}" 
    - name: Start container from compose 
      docker_compose:
        project_src: /home/pedro
        


    