---
- name: Install acl node and npm
  hosts: servers
  become: True
  tasks:
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install nodejs and npm
    apt:
      pkg:
        - acl
        - nodejs
        - npm


- name: Create new Linux user for node app
  hosts: servers
  vars_files:
    - project-vars
  become: true
  tasks:
    - name: Create Linux user
      user:
        name: "{{nodejs_user}}"
        comment: NodeJS Admin
        group: admin
      register: user_creation_result
    - debug: msg={{user_creation_result}}


- name: Deploy nodejs app
  hosts: servers
  become: yes
  become_user: "{{nodejs_user}}"
  vars_files:
    - project-vars
  tasks:
    - name: Unpack the nodejs tar file
      unarchive: 
        src: "{{location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}" 
    - name: Install dependencies
      npm:
        path: "{{user_home_dir}}/package"
    - name: Start the application
      command: 
        chdir: "{{user_home_dir}}/package/app "
        cmd: node server
      async: 1000    
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}  

