# Note: contains password
---
- name: Install python3, docker, Docker-compose, docker python module and start docker
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3, docker, Docker-compose, docker python module and start docker
      vars:
        ansible_python_interpreter: /usr/bin/python 
      yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present      
    - name: Install Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-{{lookup('pipe', 'uname -m')}} 
        dest: /usr/local/bin/docker-compose
        mode: +x    
    - name: Start docker daemon
      systemd: 
        name: docker
        state: started
    - name: Install docker python module
      pip: 
        name: 
          - docker
          - docker-compose
    

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection


- name: Start docker containers
  hosts: docker_server
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy docker compose
      copy: 
        src: /mnt/c/Users/MA/IdeaProjects/bootcamp-java-mysql/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login: 
        registry_url: https://index.docker.io/v1/  # For Docker
        username: pmadev4
        password: "{{docker_password}}" 
    - name: Start container from compose 
      docker_compose:
        project_src: /home/ec2-user
        


    